import type { DEEPSEEK_MODELS } from '@/core/constants'
import type { Tool } from '@/core/tool'
import type { ChatCompletionTool } from '@/core/tool/types'

export interface SystemMessage {
  role: 'system'
  content: string
  name?: string
}

export interface UserMessage {
  role: 'user'
  content: string
  name?: string
}

export interface AssistantMessage {
  role: 'assistant'
  content: string | null
  name?: string
  tool_calls?: ChatCompletionTool[]
  prefix?: boolean
  reasoning_content?: string
}

export interface ToolMessage {
  role: 'tool'
  content: string
  tool_call_id: string
  name?: string
}

export type ChatMessage = SystemMessage | UserMessage | AssistantMessage | ToolMessage

export type Model = (typeof DEEPSEEK_MODELS)[number] | (string & {})

export interface StreamOptions {
  include_usage?: boolean
}

export interface ModelOptions {
  baseURL?: string
  apiKey?: string
  model?: Model
  userId?: string
  thinking?: {
    type: 'enabled' | 'disabled'
  }
  reasoningEffort?: 'high' | 'max'
  maxTokens?: number
  temperature?: number
  topP?: number
  streamOptions?: StreamOptions
  /** Request timeout in milliseconds. Defaults to 60000 (60s). */
  timeout?: number
  /** Maximum number of retries on 429/500/503 errors. Defaults to 3. */
  maxRetries?: number
  /** Enable strict mode for all tool calls. Uses the Beta endpoint and passes strict: true for all tools. */
  strict?: boolean
}

export type ResolvedModelOptions = Required<ModelOptions> & {
  baseURL: string
  apiKey: string
  model: Model
  thinking: { type: 'enabled' | 'disabled' }
  strict: boolean
}

export interface LogProbsContent {
  token: string
  logprob: number
  bytes: number[]
  top_logprobs: {
    token: string
    logprob: number
    bytes: number[]
  }[]
}

export interface LogProbs {
  content: LogProbsContent[]
  reasoning_content: LogProbsContent[]
}
/**
 * The usage statistics for the chat completion.
 */
export interface Usage {
  /**
   * Number of tokens in the generated completion.
   */
  completion_tokens: number
  /**
   * Number of tokens in the prompt.
   *
   * It equals prompt_cache_hit_tokens + prompt_cache_miss_tokens.
   */
  prompt_tokens: number
  /**
   * Number of tokens in the prompt that hits the context cache.
   */
  prompt_cache_hit_tokens: number
  /**
   * Number of tokens in the prompt that misses the context cache.
   */
  prompt_cache_miss_tokens: number
  /**
   * Total number of tokens used in the request (prompt + completion).
   */
  total_tokens: number
  /**
   * Breakdown of tokens used in a completion.
   */
  completion_tokens_details: {
    /**
     * Tokens generated by the model for reasoning.
     */
    reasoning_tokens: number
  }
}

export interface ChatCompletionChoice {
  /**
   * The reason the model stopped generating tokens.
   *
   * This will be stop if the model hit a natural stop point or a provided stop sequence,
   * length if the maximum number of tokens specified in the request was reached,
   * content_filter if content was omitted due to a flag from our content filters,
   * tool_calls if the model called a tool,
   * or insufficient_system_resource if the request is interrupted due to insufficient resource of the inference system.
   */
  finish_reason: 'stop' | 'length' | 'content_filter' | 'tool_calls' | 'insufficient_system_resource'
  /**
   * The index of the choice in the list of choices.
   */
  index: number
  /**
   * A chat completion message generated by the model.
   */
  message: {
    /**
     * The contents of the message.
     */
    content: string | null
    /**
     * For thinking mode only.
     *
     * The reasoning contents of the assistant message, before the final answer.
     */
    reasoning_content: string | null
    /**
     * The tool calls generated by the model.
     */
    tool_calls: ChatCompletionTool[]
    /**
     * The role of the author of this message.
     */
    role: 'assistant'
  }
  logprobs: LogProbs | null
}

export interface ChatCompletion {
  /**
   * A unique identifier for the chat completion.
   */
  id: string
  /**
   * A list of chat completion choices.
   */
  choices: ChatCompletionChoice[]
  /**
   * The Unix timestamp (in seconds) of when the chat completion was created.
   */
  created: number
  /**
   * The model used to generate the chat completion.
   */
  model: Model
  /**
   * This fingerprint represents the backend configuration that the model runs with.
   */
  system_fingerprint: string
  /**
   * The object type, which is always chat.completion.
   */
  object: 'chat.completion'
  /**
   * The usage statistics for the chat completion.
   */
  usage: Usage
}

export interface ChatCompletionChunkDelta {
  role?: 'assistant'
  content?: string
  reasoning_content?: string
  tool_calls?: {
    index: number
    id?: string
    type?: 'function'
    function?: {
      name?: string
      arguments?: string
    }
  }[]
}

export interface ChatCompletionChunkChoice {
  index: number
  delta: ChatCompletionChunkDelta
  finish_reason: 'stop' | 'length' | 'content_filter' | 'tool_calls' | 'insufficient_system_resource' | null
}

export interface ChatCompletionChunk {
  id: string
  object: 'chat.completion.chunk'
  created: number
  model: Model
  choices: ChatCompletionChunkChoice[]
  usage?: Usage | null
}

/**
 * The model identifier, which can be referenced in the API endpoints.
 */
export interface ModelInfo {
  /** The model identifier, which can be referenced in the API endpoints. */
  id: string
  /** The object type, which is always "model". */
  object: 'model'
  /** The organization that owns the model. */
  owned_by: string
}

/** A list of models. */
export interface ListModelsResponse {
  object: 'list'
  data: ModelInfo[]
}

export interface BalanceInfo {
  /** The currency of the balance. */
  currency: 'CNY' | 'USD'
  /** The total available balance, including the granted balance and the topped-up balance. */
  total_balance: string
  /** The total not expired granted balance. */
  granted_balance: string
  /** The total topped-up balance. */
  topped_up_balance: string
}

/** User balance info. */
export interface UserBalanceResponse {
  /** Whether the user's balance is sufficient for API calls. */
  is_available: boolean
  balance_infos: BalanceInfo[]
}

export interface InvokeParams {
  messages: ChatMessage[]
  response_format?: {
    type: 'json_object'
  }
  tools?: Tool[]
  stop?: string | string[]
  logprobs?: boolean
  topLogprobs?: number
  signal?: AbortSignal
}
