import type { z } from 'zod'
import type { Model } from '@/core/model/types'

export type ToolResult = unknown

export interface ToolExecutionError extends Error {
  recoverable: false
}

export interface ToolSuccess<T = unknown> {
  success: true
  data: T
}

export interface ToolFailure {
  success: false
  error: string
}

export type ToolResultType = ToolSuccess | ToolFailure

export interface ToolCompactConfig {
  threshold?: number
  model?: Model
}

export interface StrictToolDefinition<T extends z.ZodObject> {
  name: string
  description: string
  strict: true
  required?: boolean
  schema: T
  execute: (args: z.infer<T>) => ToolResult | Promise<ToolResult>
  timeout?: number
  retries?: number
  compact?: boolean | ToolCompactConfig
}

export interface NonStrictToolDefinition<T extends z.ZodObject> {
  name: string
  description: string
  strict?: false
  required?: boolean
  schema: T
  execute: (args: z.infer<T>) => ToolResult | Promise<ToolResult>
  timeout?: number
  retries?: number
  compact?: boolean | ToolCompactConfig
}

export type ToolDefinition<
  T extends z.ZodObject,
  TStrict extends boolean | undefined = undefined,
> = TStrict extends true
  ? StrictToolDefinition<T>
  : NonStrictToolDefinition<T>

export interface ToolCall {
  type: 'function'
  function: {
    name: string
    description: string
    parameters: Record<string, any>
    strict?: boolean
  }
}

export type ToolChoice = 'auto' | 'none' | 'required' | {
  type: 'function'
  function: {
    name: string
  }
}

/**
 * The tool calls generated by the model.
 */
export interface ChatCompletionTool {
  /**
   * The ID of the tool call.
   */
  id: string
  /**
   * The type of the tool. Currently, only **function** is supported.
   */
  type: 'function'
  /**
   * The function that the model called.
   */
  function: {
    /**
     * The name of the function to call.
     */
    name: string
    /**
     * The arguments to call the function with, as generated by the model in JSON format.
     *
     * Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema.
     *
     * Validate the arguments in your code before calling your function.
     */
    arguments: string
  }
}

export interface StrictTool {
  name: string
  description: string
  strict: true
  required?: boolean
  schema: z.ZodObject
  parameters: Record<string, any>
  execute: (args: string, signal?: AbortSignal, runner?: any, hooks?: any) => Promise<string>
  timeout?: number
  retries?: number
  compact?: boolean | ToolCompactConfig
}

export interface NonStrictTool {
  name: string
  description: string
  strict?: undefined | false
  required?: boolean
  schema: z.ZodObject
  parameters: Record<string, any>
  execute: (args: string, signal?: AbortSignal, runner?: any, hooks?: any) => Promise<string>
  timeout?: number
  retries?: number
  compact?: boolean | ToolCompactConfig
}

export type ConsistentTools = StrictTool[] | NonStrictTool[]
