import type { DeepSeekModel } from '@/core/model'

export interface FIMParams {
  model: DeepSeekModel
  prompt: string
  echo?: boolean
  maxTokens?: number
  suffix?: string
}

/**
 * Log probabilities information for the completion
 */
export interface FIMLogprobs {
  /** Text offset */
  text_offset: number[]
  /** Token log probabilities */
  token_logprobs: number[]
  /** Tokens */
  tokens: string[]
  /** Top log probabilities */
  top_logprobs: Record<string, number>[]
}

/**
 * Completion choice generated by the model
 */
export interface FIMChoice {
  /**
   * The reason the model stopped generating tokens.
   * This will be `stop` if the model hit a natural stop point or a provided stop sequence,
   * `length` if the maximum number of tokens specified in the request was reached,
   * `content_filter` if content was omitted due to a flag from our content filters,
   * or `insufficient_system_resource` if the request is interrupted due to insufficient resource of the inference system.
   */
  finish_reason: 'stop' | 'length' | 'content_filter' | 'insufficient_system_resource'
  /** Index */
  index: number
  /** Log probabilities information */
  logprobs: FIMLogprobs | null
  /** Generated text */
  text: string
}

/**
 * Breakdown of tokens used in a completion
 */
export interface FIMCompletionTokensDetails {
  /** Tokens generated by the model for reasoning */
  reasoning_tokens: number
}

/**
 * Usage statistics for the completion request
 */
export interface FIMUsage {
  /** Number of tokens in the generated completion */
  completion_tokens: number
  /** Number of tokens in the prompt. It equals prompt_cache_hit_tokens + prompt_cache_miss_tokens */
  prompt_tokens: number
  /** Number of tokens in the prompt that hits the context cache */
  prompt_cache_hit_tokens: number
  /** Number of tokens in the prompt that misses the context cache */
  prompt_cache_miss_tokens: number
  /** Total number of tokens used in the request (prompt + completion) */
  total_tokens: number
  /** Breakdown of tokens used in a completion */
  completion_tokens_details: FIMCompletionTokensDetails
}

/**
 * FIM Completion API response
 */
export interface FIMResponse {
  /** A unique identifier for the completion */
  id: string
  /** The list of completion choices the model generated for the input prompt */
  choices: FIMChoice[]
  /** The Unix timestamp (in seconds) of when the completion was created */
  created: number
  /** The model used for completion */
  model: string
  /** This fingerprint represents the backend configuration that the model runs with */
  system_fingerprint: string
  /** The object type, which is always "text_completion" */
  object: 'text_completion'
  /** Usage statistics for the completion request */
  usage: FIMUsage
}
